spring.application.name=secureBlogTest


#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url = jdbc:mysql://127.0.0.1:3306/secureBlogTest?createDatabaseIfNotExist=true
spring.datasource.username=atharva.haptiq
spring.datasource.password=pass1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#spring.security.user.name=admin
#spring.security.user.password=admin123

spring.app.jwtSecret= Aakjakdheh1jenb3y4u32briuewgfiewhr9843r43iur4y38t4h2f83h4387f3gf2982gf32fcdc38r32r3wd
spring.app.jwtExpirationMs=3000000000000

#debug
logging.level.org.springframework.security=DEBUG